name: "Drop Staging Repository on Maven Central OSSRH"
description: "Drops a Sonatype staging repository on Maven Central."

branding:
  icon: "arrow-down"
  color: "purple"

inputs:
  repo-id:
    description: "The repository id to drop."
    required: true
  maven-central-username:
    description: "Sonatype Username for Maven Central."
    required: true
  maven-central-password:
    description: "Sonatype Password for Maven Central."
    required: true

runs:
  using: "composite"
  steps:
    - name: "Drop a staging repository"
      shell: bash
      env:
        NEXUS_URL: https://s01.oss.sonatype.org/service/local/staging/profiles
        REPO_ID: ${{ inputs.repo-id }}
        CREDENTIALS: ${{ inputs.maven-central-username }}:${{ inputs.maven-central-password }}
      run: |
        echo "::debug::Dropping staging repo: $REPO_ID"
        curl \
          --request POST \
          --url "https://s01.oss.sonatype.org/service/local/staging/bulk/drop" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --data '{"data":{"stagedRepositoryIds":["'$REPO_ID'"]}}' \
          --user "$CREDENTIALS"
