name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  success:
    strategy:
      matrix:
        os: [ windows-2022, macos-14, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: danysk/action-create-ossrh-staging-repo@1.0.0
        id: create-staging-repo
        with:
          group-id: "org.danilopianini"
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      - name: Check out code
        uses: actions/checkout@v4.2.2
      - name: Drop staging repository
        uses: ./
        with:
          repo-id: ${{ steps.create-staging-repo.staging-repo-id }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      - name: Install Node
        uses: actions/setup-node@v4.1.0
        if: runner.os == 'linux'
        with:
          node-version-file: package.json
      - run: npm install
        if: runner.os == 'linux'
      - run: npx semantic-release
        if: runner.os == 'linux'
        env:
          GITHUB_TOKEN: ${{ github.token }}
